<?php
/**
 * ArrecadacaoqrcodesIdBody
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * PIX-BB
 *
 * API para gerenciar os serviços referentes ao PIX (Sistema de Pagamentos Instantâneos) no BB.
 *
 * OpenAPI spec version: 1.8
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.29
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * ArrecadacaoqrcodesIdBody Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ArrecadacaoqrcodesIdBody implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'arrecadacaoqrcodes_id_body';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'numero_convenio' => 'int',
'indicador_codigo_barras' => 'string',
'codigo_guia_recebimento' => 'string',
'email_devedor' => 'string',
'codigo_pais_telefone_devedor' => 'int',
'ddd_telefone_devedor' => 'int',
'numero_telefone_devedor' => 'string',
'codigo_solicitacao_banco_central_brasil' => 'string',
'descricao_solicitacao_pagamento' => 'string',
'valor_original_solicitacao' => 'float',
'cpf_devedor' => 'string',
'cnpj_devedor' => 'string',
'nome_devedor' => 'string',
'quantidade_segundo_expiracao' => 'int',
'lista_informacao_adicional' => '\Swagger\Client\Model\ArrecadacaoqrcodesidListaInformacaoAdicional[]'    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'numero_convenio' => 'int32',
'indicador_codigo_barras' => null,
'codigo_guia_recebimento' => null,
'email_devedor' => null,
'codigo_pais_telefone_devedor' => 'int32',
'ddd_telefone_devedor' => 'int32',
'numero_telefone_devedor' => 'int32',
'codigo_solicitacao_banco_central_brasil' => null,
'descricao_solicitacao_pagamento' => null,
'valor_original_solicitacao' => 'float',
'cpf_devedor' => null,
'cnpj_devedor' => null,
'nome_devedor' => null,
'quantidade_segundo_expiracao' => 'int32',
'lista_informacao_adicional' => null    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'numero_convenio' => 'numeroConvenio',
'indicador_codigo_barras' => 'indicadorCodigoBarras',
'codigo_guia_recebimento' => 'codigoGuiaRecebimento',
'email_devedor' => 'emailDevedor',
'codigo_pais_telefone_devedor' => 'codigoPaisTelefoneDevedor',
'ddd_telefone_devedor' => 'dddTelefoneDevedor',
'numero_telefone_devedor' => 'numeroTelefoneDevedor',
'codigo_solicitacao_banco_central_brasil' => 'codigoSolicitacaoBancoCentralBrasil',
'descricao_solicitacao_pagamento' => 'descricaoSolicitacaoPagamento',
'valor_original_solicitacao' => 'valorOriginalSolicitacao',
'cpf_devedor' => 'cpfDevedor',
'cnpj_devedor' => 'cnpjDevedor',
'nome_devedor' => 'nomeDevedor',
'quantidade_segundo_expiracao' => 'quantidadeSegundoExpiracao',
'lista_informacao_adicional' => 'listaInformacaoAdicional'    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'numero_convenio' => 'setNumeroConvenio',
'indicador_codigo_barras' => 'setIndicadorCodigoBarras',
'codigo_guia_recebimento' => 'setCodigoGuiaRecebimento',
'email_devedor' => 'setEmailDevedor',
'codigo_pais_telefone_devedor' => 'setCodigoPaisTelefoneDevedor',
'ddd_telefone_devedor' => 'setDddTelefoneDevedor',
'numero_telefone_devedor' => 'setNumeroTelefoneDevedor',
'codigo_solicitacao_banco_central_brasil' => 'setCodigoSolicitacaoBancoCentralBrasil',
'descricao_solicitacao_pagamento' => 'setDescricaoSolicitacaoPagamento',
'valor_original_solicitacao' => 'setValorOriginalSolicitacao',
'cpf_devedor' => 'setCpfDevedor',
'cnpj_devedor' => 'setCnpjDevedor',
'nome_devedor' => 'setNomeDevedor',
'quantidade_segundo_expiracao' => 'setQuantidadeSegundoExpiracao',
'lista_informacao_adicional' => 'setListaInformacaoAdicional'    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'numero_convenio' => 'getNumeroConvenio',
'indicador_codigo_barras' => 'getIndicadorCodigoBarras',
'codigo_guia_recebimento' => 'getCodigoGuiaRecebimento',
'email_devedor' => 'getEmailDevedor',
'codigo_pais_telefone_devedor' => 'getCodigoPaisTelefoneDevedor',
'ddd_telefone_devedor' => 'getDddTelefoneDevedor',
'numero_telefone_devedor' => 'getNumeroTelefoneDevedor',
'codigo_solicitacao_banco_central_brasil' => 'getCodigoSolicitacaoBancoCentralBrasil',
'descricao_solicitacao_pagamento' => 'getDescricaoSolicitacaoPagamento',
'valor_original_solicitacao' => 'getValorOriginalSolicitacao',
'cpf_devedor' => 'getCpfDevedor',
'cnpj_devedor' => 'getCnpjDevedor',
'nome_devedor' => 'getNomeDevedor',
'quantidade_segundo_expiracao' => 'getQuantidadeSegundoExpiracao',
'lista_informacao_adicional' => 'getListaInformacaoAdicional'    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['numero_convenio'] = isset($data['numero_convenio']) ? $data['numero_convenio'] : null;
        $this->container['indicador_codigo_barras'] = isset($data['indicador_codigo_barras']) ? $data['indicador_codigo_barras'] : null;
        $this->container['codigo_guia_recebimento'] = isset($data['codigo_guia_recebimento']) ? $data['codigo_guia_recebimento'] : null;
        $this->container['email_devedor'] = isset($data['email_devedor']) ? $data['email_devedor'] : null;
        $this->container['codigo_pais_telefone_devedor'] = isset($data['codigo_pais_telefone_devedor']) ? $data['codigo_pais_telefone_devedor'] : null;
        $this->container['ddd_telefone_devedor'] = isset($data['ddd_telefone_devedor']) ? $data['ddd_telefone_devedor'] : null;
        $this->container['numero_telefone_devedor'] = isset($data['numero_telefone_devedor']) ? $data['numero_telefone_devedor'] : null;
        $this->container['codigo_solicitacao_banco_central_brasil'] = isset($data['codigo_solicitacao_banco_central_brasil']) ? $data['codigo_solicitacao_banco_central_brasil'] : null;
        $this->container['descricao_solicitacao_pagamento'] = isset($data['descricao_solicitacao_pagamento']) ? $data['descricao_solicitacao_pagamento'] : null;
        $this->container['valor_original_solicitacao'] = isset($data['valor_original_solicitacao']) ? $data['valor_original_solicitacao'] : null;
        $this->container['cpf_devedor'] = isset($data['cpf_devedor']) ? $data['cpf_devedor'] : null;
        $this->container['cnpj_devedor'] = isset($data['cnpj_devedor']) ? $data['cnpj_devedor'] : null;
        $this->container['nome_devedor'] = isset($data['nome_devedor']) ? $data['nome_devedor'] : null;
        $this->container['quantidade_segundo_expiracao'] = isset($data['quantidade_segundo_expiracao']) ? $data['quantidade_segundo_expiracao'] : null;
        $this->container['lista_informacao_adicional'] = isset($data['lista_informacao_adicional']) ? $data['lista_informacao_adicional'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['numero_convenio'] === null) {
            $invalidProperties[] = "'numero_convenio' can't be null";
        }
        if ($this->container['indicador_codigo_barras'] === null) {
            $invalidProperties[] = "'indicador_codigo_barras' can't be null";
        }
        if ($this->container['codigo_guia_recebimento'] === null) {
            $invalidProperties[] = "'codigo_guia_recebimento' can't be null";
        }
        if ($this->container['codigo_solicitacao_banco_central_brasil'] === null) {
            $invalidProperties[] = "'codigo_solicitacao_banco_central_brasil' can't be null";
        }
        if ($this->container['valor_original_solicitacao'] === null) {
            $invalidProperties[] = "'valor_original_solicitacao' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets numero_convenio
     *
     * @return int
     */
    public function getNumeroConvenio()
    {
        return $this->container['numero_convenio'];
    }

    /**
     * Sets numero_convenio
     *
     * @param int $numero_convenio Refere-se ao número de convênio de arrecadação de um Ente Público com o Banco do Brasil e possui até 6 posições numéricas.
     *
     * @return $this
     */
    public function setNumeroConvenio($numero_convenio)
    {
        $this->container['numero_convenio'] = $numero_convenio;

        return $this;
    }

    /**
     * Gets indicador_codigo_barras
     *
     * @return string
     */
    public function getIndicadorCodigoBarras()
    {
        return $this->container['indicador_codigo_barras'];
    }

    /**
     * Sets indicador_codigo_barras
     *
     * @param string $indicador_codigo_barras Informe S (sim) caso envie um código de barras padrão Febraban no campo seguinte (codigoGuiaRecebimento) ou N (não) caso não seja informado um código de barras mas apenas um código para conciliação.
     *
     * @return $this
     */
    public function setIndicadorCodigoBarras($indicador_codigo_barras)
    {
        $this->container['indicador_codigo_barras'] = $indicador_codigo_barras;

        return $this;
    }

    /**
     * Gets codigo_guia_recebimento
     *
     * @return string
     */
    public function getCodigoGuiaRecebimento()
    {
        return $this->container['codigo_guia_recebimento'];
    }

    /**
     * Sets codigo_guia_recebimento
     *
     * @param string $codigo_guia_recebimento Código de Barras padrão Febraban de 44 posições (se S no indicadorCodigoBarras) ou outro identificador do cliente  (se N no indicadorCodigoBarras).  O código de barras deverá ser gerado para o Número de Convênio informado no campo “NumeroConvenio”.
     *
     * @return $this
     */
    public function setCodigoGuiaRecebimento($codigo_guia_recebimento)
    {
        $this->container['codigo_guia_recebimento'] = $codigo_guia_recebimento;

        return $this;
    }

    /**
     * Gets email_devedor
     *
     * @return string
     */
    public function getEmailDevedor()
    {
        return $this->container['email_devedor'];
    }

    /**
     * Sets email_devedor
     *
     * @param string $email_devedor E-mail do devedor para contato
     *
     * @return $this
     */
    public function setEmailDevedor($email_devedor)
    {
        $this->container['email_devedor'] = $email_devedor;

        return $this;
    }

    /**
     * Gets codigo_pais_telefone_devedor
     *
     * @return int
     */
    public function getCodigoPaisTelefoneDevedor()
    {
        return $this->container['codigo_pais_telefone_devedor'];
    }

    /**
     * Sets codigo_pais_telefone_devedor
     *
     * @param int $codigo_pais_telefone_devedor Código do País do Telefone do Devedor
     *
     * @return $this
     */
    public function setCodigoPaisTelefoneDevedor($codigo_pais_telefone_devedor)
    {
        $this->container['codigo_pais_telefone_devedor'] = $codigo_pais_telefone_devedor;

        return $this;
    }

    /**
     * Gets ddd_telefone_devedor
     *
     * @return int
     */
    public function getDddTelefoneDevedor()
    {
        return $this->container['ddd_telefone_devedor'];
    }

    /**
     * Sets ddd_telefone_devedor
     *
     * @param int $ddd_telefone_devedor DDD do telefone do devedor
     *
     * @return $this
     */
    public function setDddTelefoneDevedor($ddd_telefone_devedor)
    {
        $this->container['ddd_telefone_devedor'] = $ddd_telefone_devedor;

        return $this;
    }

    /**
     * Gets numero_telefone_devedor
     *
     * @return string
     */
    public function getNumeroTelefoneDevedor()
    {
        return $this->container['numero_telefone_devedor'];
    }

    /**
     * Sets numero_telefone_devedor
     *
     * @param string $numero_telefone_devedor Numero do telefone do devedor
     *
     * @return $this
     */
    public function setNumeroTelefoneDevedor($numero_telefone_devedor)
    {
        $this->container['numero_telefone_devedor'] = $numero_telefone_devedor;

        return $this;
    }

    /**
     * Gets codigo_solicitacao_banco_central_brasil
     *
     * @return string
     */
    public function getCodigoSolicitacaoBancoCentralBrasil()
    {
        return $this->container['codigo_solicitacao_banco_central_brasil'];
    }

    /**
     * Sets codigo_solicitacao_banco_central_brasil
     *
     * @param string $codigo_solicitacao_banco_central_brasil Refere-se à Chave Pix do Recebedor cadastrada no Banco do Brasil. O campo é obrigatório. Em ambiente de produção, a Chave Pix deverá estar vinculada a uma conta cujo CNPJ seja o mesmo utilizado na credencial de acesso à API. Em ambiente de homologação, use as chaves Pix criadas para usuários testes. A chave será lida pelo aplicativo do PSP do pagador para consulta ao DICT que retornará a informação e identificará o recebedor da arrecadação.
     *
     * @return $this
     */
    public function setCodigoSolicitacaoBancoCentralBrasil($codigo_solicitacao_banco_central_brasil)
    {
        $this->container['codigo_solicitacao_banco_central_brasil'] = $codigo_solicitacao_banco_central_brasil;

        return $this;
    }

    /**
     * Gets descricao_solicitacao_pagamento
     *
     * @return string
     */
    public function getDescricaoSolicitacaoPagamento()
    {
        return $this->container['descricao_solicitacao_pagamento'];
    }

    /**
     * Sets descricao_solicitacao_pagamento
     *
     * @param string $descricao_solicitacao_pagamento Determina um texto a ser apresentado ao pagador em formato livre limitado a 140 caracteres.
     *
     * @return $this
     */
    public function setDescricaoSolicitacaoPagamento($descricao_solicitacao_pagamento)
    {
        $this->container['descricao_solicitacao_pagamento'] = $descricao_solicitacao_pagamento;

        return $this;
    }

    /**
     * Gets valor_original_solicitacao
     *
     * @return float
     */
    public function getValorOriginalSolicitacao()
    {
        return $this->container['valor_original_solicitacao'];
    }

    /**
     * Sets valor_original_solicitacao
     *
     * @param float $valor_original_solicitacao Valor original do documento. O valor do QRCode deverá, obrigatoriamente, corresponder ao valor registrado no código de barras.
     *
     * @return $this
     */
    public function setValorOriginalSolicitacao($valor_original_solicitacao)
    {
        $this->container['valor_original_solicitacao'] = $valor_original_solicitacao;

        return $this;
    }

    /**
     * Gets cpf_devedor
     *
     * @return string
     */
    public function getCpfDevedor()
    {
        return $this->container['cpf_devedor'];
    }

    /**
     * Sets cpf_devedor
     *
     * @param string $cpf_devedor Determina o CPF do devedor, caso haja. O campo não é obrigatório, porém, se informado, o campo NomeDevedor também deverá ser preenchido. Este campo não poderá ser informado, caso o campo cnpjDevedor contenha dados. Para fins de testes, usar os CPF da seção de dados para testes do portal BB Developers.
     *
     * @return $this
     */
    public function setCpfDevedor($cpf_devedor)
    {
        $this->container['cpf_devedor'] = $cpf_devedor;

        return $this;
    }

    /**
     * Gets cnpj_devedor
     *
     * @return string
     */
    public function getCnpjDevedor()
    {
        return $this->container['cnpj_devedor'];
    }

    /**
     * Sets cnpj_devedor
     *
     * @param string $cnpj_devedor Determina o CNPJ do devedor, caso haja. O campo não é obrigatório, porém se informado, o campo NomeDevedor também deverá ser preenchido. Este campo não poderá ser informado, caso o campo cpfDevedor contenha dados. Para fins de testes, usar os CNPJ da seção de dados para testes do portal BB Developers.
     *
     * @return $this
     */
    public function setCnpjDevedor($cnpj_devedor)
    {
        $this->container['cnpj_devedor'] = $cnpj_devedor;

        return $this;
    }

    /**
     * Gets nome_devedor
     *
     * @return string
     */
    public function getNomeDevedor()
    {
        return $this->container['nome_devedor'];
    }

    /**
     * Sets nome_devedor
     *
     * @param string $nome_devedor Determina o nome da instituição ou pessoa a quem a cobrança está endereçada. O preenchimento do campo \"Nome Devedor\" é obrigatório se o campo \"Numero CPF Devedor\" ou o campo \"Numero Cadastro Nac Pessoas Juridicas Devedor\" estiver preenchido
     *
     * @return $this
     */
    public function setNomeDevedor($nome_devedor)
    {
        $this->container['nome_devedor'] = $nome_devedor;

        return $this;
    }

    /**
     * Gets quantidade_segundo_expiracao
     *
     * @return int
     */
    public function getQuantidadeSegundoExpiracao()
    {
        return $this->container['quantidade_segundo_expiracao'];
    }

    /**
     * Sets quantidade_segundo_expiracao
     *
     * @param int $quantidade_segundo_expiracao Duração que indica limite, com granularidade de segundos, para que o pagamento do QR Code possa ser realizado, a partir da data-hora de criação. Deve ser utilizado como espécie de data de vencimentos em segundos que deverá ser calculada da data-hora de criação até a data-hora de vencimento. Caso não informado, assume-se a duração de 86400 segundos, que corresponde a 24 horas.
     *
     * @return $this
     */
    public function setQuantidadeSegundoExpiracao($quantidade_segundo_expiracao)
    {
        $this->container['quantidade_segundo_expiracao'] = $quantidade_segundo_expiracao;

        return $this;
    }

    /**
     * Gets lista_informacao_adicional
     *
     * @return \Swagger\Client\Model\ArrecadacaoqrcodesidListaInformacaoAdicional[]
     */
    public function getListaInformacaoAdicional()
    {
        return $this->container['lista_informacao_adicional'];
    }

    /**
     * Sets lista_informacao_adicional
     *
     * @param \Swagger\Client\Model\ArrecadacaoqrcodesidListaInformacaoAdicional[] $lista_informacao_adicional O campo \"listaInformacaoAdicional\", se estiver presente, se refere a uma lista em que cada elemento deve utilizar o esquema abaixo:
     *
     * @return $this
     */
    public function setListaInformacaoAdicional($lista_informacao_adicional)
    {
        $this->container['lista_informacao_adicional'] = $lista_informacao_adicional;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
