<?php
/**
 * ArrecadacaoqrcodesIdBodyTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * PIX-BB
 *
 * API para gerenciar os serviços referentes ao PIX (Sistema de Pagamentos Instantâneos) no BB.
 *
 * OpenAPI spec version: 1.8
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.29
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ArrecadacaoqrcodesIdBodyTest Class Doc Comment
 *
 * @category    Class
 * @description ArrecadacaoqrcodesIdBody
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ArrecadacaoqrcodesIdBodyTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ArrecadacaoqrcodesIdBody"
     */
    public function testArrecadacaoqrcodesIdBody()
    {
    }

    /**
     * Test attribute "numero_convenio"
     */
    public function testPropertyNumeroConvenio()
    {
    }

    /**
     * Test attribute "indicador_codigo_barras"
     */
    public function testPropertyIndicadorCodigoBarras()
    {
    }

    /**
     * Test attribute "codigo_guia_recebimento"
     */
    public function testPropertyCodigoGuiaRecebimento()
    {
    }

    /**
     * Test attribute "email_devedor"
     */
    public function testPropertyEmailDevedor()
    {
    }

    /**
     * Test attribute "codigo_pais_telefone_devedor"
     */
    public function testPropertyCodigoPaisTelefoneDevedor()
    {
    }

    /**
     * Test attribute "ddd_telefone_devedor"
     */
    public function testPropertyDddTelefoneDevedor()
    {
    }

    /**
     * Test attribute "numero_telefone_devedor"
     */
    public function testPropertyNumeroTelefoneDevedor()
    {
    }

    /**
     * Test attribute "codigo_solicitacao_banco_central_brasil"
     */
    public function testPropertyCodigoSolicitacaoBancoCentralBrasil()
    {
    }

    /**
     * Test attribute "descricao_solicitacao_pagamento"
     */
    public function testPropertyDescricaoSolicitacaoPagamento()
    {
    }

    /**
     * Test attribute "valor_original_solicitacao"
     */
    public function testPropertyValorOriginalSolicitacao()
    {
    }

    /**
     * Test attribute "cpf_devedor"
     */
    public function testPropertyCpfDevedor()
    {
    }

    /**
     * Test attribute "cnpj_devedor"
     */
    public function testPropertyCnpjDevedor()
    {
    }

    /**
     * Test attribute "nome_devedor"
     */
    public function testPropertyNomeDevedor()
    {
    }

    /**
     * Test attribute "quantidade_segundo_expiracao"
     */
    public function testPropertyQuantidadeSegundoExpiracao()
    {
    }

    /**
     * Test attribute "lista_informacao_adicional"
     */
    public function testPropertyListaInformacaoAdicional()
    {
    }
}
