<?php
/**
 * IdBaixarBodyTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * PIX-BB
 *
 * API para gerenciar os serviços referentes ao PIX (Sistema de Pagamentos Instantâneos) no BB.
 *
 * OpenAPI spec version: 1.8
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.29
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * IdBaixarBodyTest Class Doc Comment
 *
 * @category    Class
 * @description IdBaixarBody
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class IdBaixarBodyTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "IdBaixarBody"
     */
    public function testIdBaixarBody()
    {
    }

    /**
     * Test attribute "numero_convenio"
     */
    public function testPropertyNumeroConvenio()
    {
    }

    /**
     * Test attribute "codigo_solicitacao_banco_central_brasil"
     */
    public function testPropertyCodigoSolicitacaoBancoCentralBrasil()
    {
    }

    /**
     * Test attribute "cpf_devedor"
     */
    public function testPropertyCpfDevedor()
    {
    }

    /**
     * Test attribute "cnpj_devedor"
     */
    public function testPropertyCnpjDevedor()
    {
    }
}
