<?php
/**
 * InlineResponse201Test
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * PIX-BB
 *
 * API para gerenciar os serviços referentes ao PIX (Sistema de Pagamentos Instantâneos) no BB.
 *
 * OpenAPI spec version: 1.8
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.29
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * InlineResponse201Test Class Doc Comment
 *
 * @category    Class
 * @description InlineResponse201
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class InlineResponse201Test extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "InlineResponse201"
     */
    public function testInlineResponse201()
    {
    }

    /**
     * Test attribute "timestamp_criacao_solicitacao"
     */
    public function testPropertyTimestampCriacaoSolicitacao()
    {
    }

    /**
     * Test attribute "estado_solicitacao"
     */
    public function testPropertyEstadoSolicitacao()
    {
    }

    /**
     * Test attribute "codigo_conciliacao_solicitante"
     */
    public function testPropertyCodigoConciliacaoSolicitante()
    {
    }

    /**
     * Test attribute "numero_versao_solicitacao_pagamento"
     */
    public function testPropertyNumeroVersaoSolicitacaoPagamento()
    {
    }

    /**
     * Test attribute "link_qr_code"
     */
    public function testPropertyLinkQrCode()
    {
    }

    /**
     * Test attribute "qr_code"
     */
    public function testPropertyQrCode()
    {
    }
}
