<?php
/**
 * InlineResponse200Test
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * PIX-BB
 *
 * API para gerenciar os serviços referentes ao PIX (Sistema de Pagamentos Instantâneos) no BB.
 *
 * OpenAPI spec version: 1.8
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.29
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * InlineResponse200Test Class Doc Comment
 *
 * @category    Class
 * @description InlineResponse200
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class InlineResponse200Test extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "InlineResponse200"
     */
    public function testInlineResponse200()
    {
    }

    /**
     * Test attribute "codigo_conciliacao_solicitante"
     */
    public function testPropertyCodigoConciliacaoSolicitante()
    {
    }

    /**
     * Test attribute "email_devedor"
     */
    public function testPropertyEmailDevedor()
    {
    }

    /**
     * Test attribute "codigo_pais_telefone_devedor"
     */
    public function testPropertyCodigoPaisTelefoneDevedor()
    {
    }

    /**
     * Test attribute "ddd_telefone_devedor"
     */
    public function testPropertyDddTelefoneDevedor()
    {
    }

    /**
     * Test attribute "numero_telefone_devedor"
     */
    public function testPropertyNumeroTelefoneDevedor()
    {
    }

    /**
     * Test attribute "timestamp_criacao_solicitacao"
     */
    public function testPropertyTimestampCriacaoSolicitacao()
    {
    }

    /**
     * Test attribute "quantidade_segundo_expiracao"
     */
    public function testPropertyQuantidadeSegundoExpiracao()
    {
    }

    /**
     * Test attribute "estado_solicitacao"
     */
    public function testPropertyEstadoSolicitacao()
    {
    }

    /**
     * Test attribute "numero_versao_solicitacao_pagamento"
     */
    public function testPropertyNumeroVersaoSolicitacaoPagamento()
    {
    }

    /**
     * Test attribute "link_qr_code"
     */
    public function testPropertyLinkQrCode()
    {
    }

    /**
     * Test attribute "qr_code"
     */
    public function testPropertyQrCode()
    {
    }

    /**
     * Test attribute "cpf_devedor"
     */
    public function testPropertyCpfDevedor()
    {
    }

    /**
     * Test attribute "cnpj_devedor"
     */
    public function testPropertyCnpjDevedor()
    {
    }

    /**
     * Test attribute "nome_devedor"
     */
    public function testPropertyNomeDevedor()
    {
    }

    /**
     * Test attribute "valor_original_solicitacao"
     */
    public function testPropertyValorOriginalSolicitacao()
    {
    }

    /**
     * Test attribute "codigo_solicitacao_banco_central_brasil"
     */
    public function testPropertyCodigoSolicitacaoBancoCentralBrasil()
    {
    }

    /**
     * Test attribute "descricao_solicitacao_pagamento"
     */
    public function testPropertyDescricaoSolicitacaoPagamento()
    {
    }

    /**
     * Test attribute "lista_informacao_adicional"
     */
    public function testPropertyListaInformacaoAdicional()
    {
    }

    /**
     * Test attribute "codigo_identificador_pagamento"
     */
    public function testPropertyCodigoIdentificadorPagamento()
    {
    }

    /**
     * Test attribute "valor_pagamento"
     */
    public function testPropertyValorPagamento()
    {
    }

    /**
     * Test attribute "timestamp_pagamento"
     */
    public function testPropertyTimestampPagamento()
    {
    }

    /**
     * Test attribute "cpf_pagador"
     */
    public function testPropertyCpfPagador()
    {
    }

    /**
     * Test attribute "cnpj_pagador"
     */
    public function testPropertyCnpjPagador()
    {
    }

    /**
     * Test attribute "nome_cliente_pagador"
     */
    public function testPropertyNomeClientePagador()
    {
    }

    /**
     * Test attribute "texto_informativo_pagador"
     */
    public function testPropertyTextoInformativoPagador()
    {
    }
}
