<?php
/**
 * InlineResponse2003Test
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * PIX-BB
 *
 * API para gerenciar os serviços referentes ao PIX (Sistema de Pagamentos Instantâneos) no BB.
 *
 * OpenAPI spec version: 1.8
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.29
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * InlineResponse2003Test Class Doc Comment
 *
 * @category    Class
 * @description InlineResponse2003
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class InlineResponse2003Test extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "InlineResponse2003"
     */
    public function testInlineResponse2003()
    {
    }

    /**
     * Test attribute "codigo_estado"
     */
    public function testPropertyCodigoEstado()
    {
    }

    /**
     * Test attribute "timestamp"
     */
    public function testPropertyTimestamp()
    {
    }

    /**
     * Test attribute "valor"
     */
    public function testPropertyValor()
    {
    }

    /**
     * Test attribute "codigo_tipo_pessoa_recebedor"
     */
    public function testPropertyCodigoTipoPessoaRecebedor()
    {
    }

    /**
     * Test attribute "cpf_cnpj_recebedor"
     */
    public function testPropertyCpfCnpjRecebedor()
    {
    }

    /**
     * Test attribute "codigo_solicitacao_banco_central_brasil"
     */
    public function testPropertyCodigoSolicitacaoBancoCentralBrasil()
    {
    }

    /**
     * Test attribute "codigo_banco_recebedor"
     */
    public function testPropertyCodigoBancoRecebedor()
    {
    }

    /**
     * Test attribute "nome_banco_recebedor"
     */
    public function testPropertyNomeBancoRecebedor()
    {
    }

    /**
     * Test attribute "codigo_tipo_pessoa_pagador"
     */
    public function testPropertyCodigoTipoPessoaPagador()
    {
    }

    /**
     * Test attribute "cpf_cnpj_pagador"
     */
    public function testPropertyCpfCnpjPagador()
    {
    }

    /**
     * Test attribute "codigo_banco_pagador"
     */
    public function testPropertyCodigoBancoPagador()
    {
    }

    /**
     * Test attribute "nome_banco_pagador"
     */
    public function testPropertyNomeBancoPagador()
    {
    }

    /**
     * Test attribute "codigo_identificador_solicitacao_pagamento_instantaneo"
     */
    public function testPropertyCodigoIdentificadorSolicitacaoPagamentoInstantaneo()
    {
    }

    /**
     * Test attribute "codigo_conciliacao_recebedor"
     */
    public function testPropertyCodigoConciliacaoRecebedor()
    {
    }

    /**
     * Test attribute "descricao_pagamento_pagador"
     */
    public function testPropertyDescricaoPagamentoPagador()
    {
    }

    /**
     * Test attribute "descricao_complementar_pagador"
     */
    public function testPropertyDescricaoComplementarPagador()
    {
    }

    /**
     * Test attribute "codigo_erro_pagamento"
     */
    public function testPropertyCodigoErroPagamento()
    {
    }

    /**
     * Test attribute "texto_erro"
     */
    public function testPropertyTextoErro()
    {
    }
}
