<?php
/**
 * InlineResponse200ListaInformacaoAdicionalTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * PIX-BB
 *
 * API para gerenciar os serviços referentes ao PIX (Sistema de Pagamentos Instantâneos) no BB.
 *
 * OpenAPI spec version: 1.8
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.29
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * InlineResponse200ListaInformacaoAdicionalTest Class Doc Comment
 *
 * @category    Class
 * @description InlineResponse200ListaInformacaoAdicional
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class InlineResponse200ListaInformacaoAdicionalTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "InlineResponse200ListaInformacaoAdicional"
     */
    public function testInlineResponse200ListaInformacaoAdicional()
    {
    }

    /**
     * Test attribute "codigo_informacao_adicional"
     */
    public function testPropertyCodigoInformacaoAdicional()
    {
    }

    /**
     * Test attribute "texto_informacao_adicional"
     */
    public function testPropertyTextoInformacaoAdicional()
    {
    }
}
