<?php
/**
 * QrCodesApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * PIX-BB
 *
 * API para gerenciar os serviços referentes ao PIX (Sistema de Pagamentos Instantâneos) no BB.
 *
 * OpenAPI spec version: 1.8
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.29
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;

/**
 * QrCodesApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class QrCodesApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for alteraQrCodeArrecadacao
     *
     * Gerenciar QRCode de Pagamento Instantâneo de uma Guia de Arrecadação.
     *
     */
    public function testAlteraQrCodeArrecadacao()
    {
    }

    /**
     * Test case for baixarQRCode
     *
     * Baixar QRCode de Pagamento Instantâneo de uma Guia de Arrecadação.
     *
     */
    public function testBaixarQRCode()
    {
    }

    /**
     * Test case for consultaQrCodeArrecadacao
     *
     * Gerenciar QRCode de Pagamento Instantâneo de uma Guia de Arrecadação.
     *
     */
    public function testConsultaQrCodeArrecadacao()
    {
    }

    /**
     * Test case for consultaQrCodeGuiaRecolhimento
     *
     * Consultar QRCode de Pagamento Instantâneo por Guia de Recebimento.
     *
     */
    public function testConsultaQrCodeGuiaRecolhimento()
    {
    }

    /**
     * Test case for criaBoletoBancarioId
     *
     * Gerar QRCode de Pagamento Instantâneo de uma Guia de Arrecadação.
     *
     */
    public function testCriaBoletoBancarioId()
    {
    }

    /**
     * Test case for pagamentosQRCodeArrecadacao
     *
     * Consulta um pagamento vinculado ao QRCode Registrado de uma Guia de Arrecadação.
     *
     */
    public function testPagamentosQRCodeArrecadacao()
    {
    }
}
